### ISSUE TITLE
Lighthouse score tracking issue

### ISSUE THREAD

**Issue by thekid** [thekid/dialog#18]
Starting point for /feed:

![Lighthouse score](https://user-images.githubusercontent.com/696742/194957066-6090908f-1520-4b69-a17b-f02d1315882e.png)

TODO:

* [ ] Investigate deprecated APIs layers - see #17 
* [ ] Image dimensions when using cards or smaller images
* [ ] Content Security Policy - #19

**Comment by thekid** [comment]
The "Journeys" page could be greatly improved by adding lazy loading for images in row 2 and below.

**Comment by thekid** [comment]
https://dialog.friebes.info/journeys now also produces a `100` score.

**Comment by thekid** [comment]
https://youtu.be/E_4vo8fSNeU

How to be fast - NDC London 2022

**Comment by thekid** [comment]
State after upgrade OpenLayers in thekid/dialog@a1182594c078ce72ffda433ee554ca014383cf44 (which results in a slightly larger JavaScript bundle size) continues to stay at **100**:

![Lighthouse score 100](https://github.com/thekid/dialog/assets/696742/1d601c80-d35a-4c27-a7d6-734ee3dc76e6)

**Comment by thekid** [comment]
https://github.com/thekid/dialog/pull/62 reduces the JavaScript loaded on the home page by more than 800 kilobytes.
